/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Mar 28 10:03:12 2026"
#define BUILD_TIME (1774706592L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x181fee4cUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x44218263UL
#define VERSION_SANITY2 0xb8d28978UL

#define VERSION_STRING "0.0.7E7F3"
#define VERSION_ID \
 "Unix SlashEM Version 0.0.7E7F3 - last build Sat Mar 28 10:03:12 2026."
