/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu Apr  2 15:14:12 2026"
#define BUILD_TIME (1775157252L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x181fee4cUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x44218263UL
#define VERSION_SANITY2 0xac89d5f0UL

#define VERSION_STRING "0.0.7E7F3"
#define VERSION_ID \
 "Unix SlashEM Version 0.0.7E7F3 - last build Thu Apr  2 15:14:12 2026."
